-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 23:54:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema programacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema programacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `programacion` DEFAULT CHARACTER SET utf8 ;
USE `programacion` ;

-- -----------------------------------------------------
-- Table `programacion`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programacion`.`Usuario` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `TipoUsuario` VARCHAR(15) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `programacion`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programacion`.`Producto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` VARCHAR(45) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
